version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: scholarship_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/backend/staticfiles

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "80:80"

volumes:
  db_data:
  static_volume:
