# Generated by Django 6.0.5 on 2026-05-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=100)),
                ('year_started', models.PositiveIntegerField()),
                ('year_ended', models.PositiveIntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_backgrounds', to='applications.scholarshipapplication')),
            ],
        ),
    ]
