# Generated by Django 6.0.5 on 2026-06-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action__b74b18_idx',
            old_name='core_audit_action_cat_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2a1528_idx',
            old_name='core_audit_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_resourc_a674ad_idx',
            old_name='core_audit_resource_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_severit_69b72f_idx',
            old_name='core_audit_severity_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
